### ISSUE TITLE
Segfault with big array

### ISSUE THREAD

**Issue by toots** [savonet/ocaml-lame#3]
Reported via the liquidsoap slack:
```gdb
#0  0x00007fc116ec068d in lame_copy_inbuffer
    (gfc=gfc@entry=0x7fc0ec003100, l=l@entry=0x7fc1103b4c48, r=r@entry=0xc00, nsamples=nsamples@entry=1764, pcm_type=pcm_type@entry=pcm_float_type, jump=jump@entry=1, s=s@entry=1) at lame.c:1865
#1  0x00007fc116ec0c9d in lame_encode_buffer_template
    (gfp=gfp@entry=0x7fc0ec002fa0, buffer_l=0x7fc1103b4c48, buffer_r=0xc00, nsamples=nsamples@entry=1764, mp3buf=mp3buf@entry=0x7fc0d8204810 "\020\250\223\330\300\177", mp3buf_size=mp3buf_size@entry=9405, pcm_type=pcm_float_type, aa=1, norm=norm@entry=1) at lame.c:1895
#2  0x00007fc116ec1aa5 in lame_encode_buffer_float
    (gfp=gfp@entry=0x7fc0ec002fa0, pcm_l=<optimized out>, pcm_r=<optimized out>, nsamples=nsamples@entry=1764, mp3buf=mp3buf@entry=0x7fc0d8204810 "\020\250\223\330\300\177", mp3buf_size=mp3buf_size@entry=9405) at lame.c:1925
#3  0x0000560bc66e129c in ocaml_lame_encode_buffer_float_ba (l=<optimized out>, _bufl=<optimized out>, _bufr=<optimized out>) at lame_stubs.c:300
#4  0x0000560bc65a9759 in camlLame__fun_505 ()
#5  0x0000560bc63bc4c8 in camlLame_encoder__encode_473 () at encoder/lame_encoder.ml:224
#6  0x0000560bc641d696 in camlOutput__output_chunks_1042 () at outputs/output.ml:260
#7  0x0000560bc641b983 in camlOutput__fun_1257 () at outputs/output.ml:186
#8  0x0000560bc652972d in camlClock__fun_1644 () at clock.ml:288
#9  0x0000560bc6677e28 in camlStdlib__list__fold_left_250 ()
#10 0x0000560bc65276d1 in camlClock__fun_1595 () at clock.ml:285
#11 0x0000560bc652940c in camlClock__loop_936 () at clock.ml:256
#12 0x0000560bc6527a2d in camlClock__fun_1572 () at clock.ml:259
#13 0x0000560bc654fd89 in camlTutils__fun_1468 () at tools/tutils.ml:157
#14 0x0000560bc666acdb in camlThread__fun_286 ()
#15 0x0000560bc6726550 in caml_start_program ()
#16 0x0000560bc67000c0 in caml_thread_start ()
#17 0x00007fc1166ac46f in start_thread () at /usr/lib/libpthread.so.0
#18 0x00007fc1165bb3d3 in clone () at /usr/lib/libc.so.6
```

**Comment by toots** [comment]
I suspect that this is the same issue as: https://github.com/savonet/ocaml-lame/issues/4
